### ISSUE TITLE
Lot hover highlight should clear on mouseout

### ISSUE THREAD

**Issue by andycochran** [NYCPlanning/labs-zola#19]
Currently, you can hover from a lot to a street (or outside the map) and the last lot you hovered remains highlighted. It should return to its default state on mouseout.

**Comment by chriswhong** [comment]
Fixed in #39

**Comment by andycochran** [comment]
Hovering off of a lot now clears that lot's highlight. However, the issue persists with hovering off the edge of the map. The lot at the edge of the map — where you hover off — remains highlighted.

**Comment by chriswhong** [comment]
Fixed in 9ecd9af29e176c3bfc29b527bf13a5ec5ac9428c
